export enum AppFeature {
  Slack = 'slack',
  SlackChannelCreation = 'slack_channel_creation',
  UnifiedSlack = 'unified_slack',
  Telegram = 'telegram',
  Email = 'email',
  LiveSettings = 'live_settings',
  CloudNotifications = 'grafana_cloud_notifications',
  CloudConnection = 'grafana_cloud_connection',
  Labels = 'labels',
  MsTeams = 'msteams',
  GoogleOauth2 = 'google_oauth2',
  PersonalWebhook = 'personal_webhook',
  Mattermost = 'mattermost',
  AllowDirectPagingCreation = 'allow_direct_paging_creation',
}
